Fix Fabric checks happening too early
kmagiera/react-native-gesture-handler pull request #1923
Opened 2022-03-09 14:10 UTC by j-piasecki

## Description

- loads `findHostInstance_DEPRECATED` lazily to prevent error
- calls `install()` method on module during the first render of `GestureHandlerRootView`, at which point we can reliably check whether Fabric is enabled

Fixes https://github.com/software-mansion/react-native-gesture-handler/issues/1920.

## Test plan

Ran FabricExample with `inlineRequires` set to `true` and `false`.

2022-03-28 16:25 UTC, tomekzaw reviewed
Looks good to me. What about [this](https://github.com/software-mansion/react-native-gesture-handler/blob/242c9af654428be7577067c8fd3c760e202008ac/src/components/GestureHandlerButton.tsx#L6-L8) conditional using `isFabric()` in top-level?

2022-03-30 18:49 UTC, tomekzaw requested changes

2022-03-30 18:49 UTC, tomekzaw commented on src/GestureHandlerRootView.android.tsx
>  const GestureHandlerRootViewNativeComponent = isFabric()
Instead of calling `isFabric()` in top-level, let's check React Native version using `import { version } from 'react-native/package.json';`.

2022-04-06 07:59 UTC, j-piasecki commented on src/init.ts
> +export function tryInitializeFabric() {
Done in https://github.com/software-mansion/react-native-gesture-handler/pull/1923/commits/e9911a6395db84c0c9ccc060ce5828bc7ffff7de.

2022-04-06 08:01 UTC, j-piasecki commented on src/GestureHandlerRootView.android.tsx
>  const GestureHandlerRootViewNativeComponent = isFabric()
Done in https://github.com/software-mansion/react-native-gesture-handler/pull/1923/commits/7d706e9675b4415e035ce39bcfeb26f8fbbff830.

2022-04-07 07:23 UTC, merged