Memoize tap GH state for sending proper value after releasing finger
kmagiera/react-native-gesture-handler pull request #478
Opened 2019-02-27 11:55 UTC by osdnk

## Motivation 
Issue happens on iOS. https://github.com/kmagiera/react-native-gesture-handler/issues/476. 

After releasing finger in tap GH which is waiting for second GH and failure of second GH, values are being set zero and then zeros are send to JS instead on corrects values.
 
## Changes
After reseting values are memoized and then could be placed in nativeEvent.

2019-03-04 09:47 UTC, kmagiera requested changes
I'd prefer if we always use memoized value for the event and memoize it in a place where we are certain the values are right. I'm not certain that the conditions you added in `eventExtraData` are going to work at all times (e.g. could there be a case that numberOfTouches is zero but the code where we memoize hasn't been triggered?)

2020-01-13 11:55 UTC, farfromrefug commented
@kmagiera i think i fixed this the way you wanted.
I actually use your Native code for a Nativescript module.
Here is the commit if that is of any interest to you
https://github.com/Akylas/nativescript-gesturehandler/commit/6c3ed76e958660ea83364f1e3e9e6fcef8e7a43b

2020-01-23 09:44 UTC, kmagiera commented
This looks more like how I'd imagine. Thanks for sending @farfromrefug. Willing to send a PR with this change maybe?

2020-01-23 09:45 UTC, farfromrefug commented
@kmagiera sorry i dont use your code nor react-native

2020-09-01 11:53 UTC, jkadamczyk commented
@kmagiera @jakub-gonet I can apply changes that @farfromrefug proposed.
Is it still relevant?

2026-04-13 14:59 UTC, m-bert commented
I'm closing this PR as the issue no longer persists on v2 and v3. Let me know if this should be reopened.

2026-04-13 14:59 UTC, closed without merging